# 公共配置文件
spring:
  application:
    name: lcoj-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: redis
    timeout: 2592000 # 30 天过期
  # todo 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lcoj
    username: root
    password: 123456
  # todo Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  freemarker:
    checkTemplateLocation: false
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000 # cookie 30 天过期
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "LCOJ接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.lc.oj.controller
# lcoj配置
lcoj:
  data-path: "xxx"
